### ISSUE TITLE
CTRL-C shutdown without stopping mount motion

### ISSUE THREAD

**Issue by bgottula** [seeing-things/track#118]
Twice on 22 Jan 2019 when I shut down hybrid_track with CTRL-C it did not fully shut down immediately, allowing the mount to continue slewing. I issued CTRL-C a second time, which emitted an error message but still left the mount in motion. I then had to start the gamepad program to finally bring the mount to a stop. This behavior could cause damage to hardware.

```
rgottula@nix ~ $ hybrid_track --meridian-side=east tle ~/Desktop/tles/SL16_RB.tle 
In TLE file mode: '/home/rgottula/Desktop/tles/SL16_RB.tle'.
Hybrid error source starting in blind tracking state
Gamepad found and registered.
Warning: loop filter update period was 0.2201 s, limit is 0.1000 s.
Warning: loop filter update period was 0.2201 s, limit is 0.1000 s.
^CGoodbye!
^CException ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

**Comment by bgottula** [comment]
This looks like it may be a duplicate of #111.

**Comment by bgottula** [comment]
Closing as duplicate of #111.
