### ISSUE TITLE
Exception during alignment

### ISSUE THREAD

**Issue by bgottula** [seeing-things/track#219]
Got the following. Note this is the first time I have tried to run an alignment after upgrading to Mint 20, so this may be the result of some change in a newer version of Pandas than what I was using previously.

```
Traceback (most recent call last):
  File "/home/rgottula/dev/venv/bin/align", line 11, in <module>
    load_entry_point('track', 'console_scripts', 'align')()
  File "/home/rgottula/dev/track/track/align.py", line 415, in main
    model_params, result = track.model.solve_model(observations)
  File "/home/rgottula/dev/track/track/model.py", line 640, in solve_model
    result = scipy.optimize.least_squares(
  File "/home/rgottula/dev/venv/lib/python3.8/site-packages/scipy/optimize/_lsq/least_squares.py", line 817, in least_squares
    f0 = fun_wrapped(x0)
  File "/home/rgottula/dev/venv/lib/python3.8/site-packages/scipy/optimize/_lsq/least_squares.py", line 812, in fun_wrapped
    return np.atleast_1d(fun(x, *args, **kwargs))
  File "/home/rgottula/dev/track/track/model.py", line 558, in residuals
    res = observations.apply(
  File "/home/rgottula/dev/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 7765, in apply
    return op.get_result()
  File "/home/rgottula/dev/venv/lib/python3.8/site-packages/pandas/core/apply.py", line 185, in get_result
    return self.apply_standard()
  File "/home/rgottula/dev/venv/lib/python3.8/site-packages/pandas/core/apply.py", line 276, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/home/rgottula/dev/venv/lib/python3.8/site-packages/pandas/core/apply.py", line 290, in apply_series_generator
    results[i] = self.f(v)
  File "/home/rgottula/dev/venv/lib/python3.8/site-packages/pandas/core/apply.py", line 110, in f
    return func(x, *args, **kwds)
TypeError: residual() got an unexpected keyword argument 'reduce'
```

**Comment by bgottula** [comment]
Fixed in 30c3e909. Tested with the same `observations` DataFrame and it worked.
