### ISSUE TITLE
OpenCV API changes

### ISSUE THREAD

**Issue by bgottula** [seeing-things/track#221]
OpenCV must have changed one or more of their APIs.

First error:
```
Traceback (most recent call last):
  File "/home/rgottula/dev/venv/bin/track", line 11, in <module>
    load_entry_point('track', 'console_scripts', 'track')()
  File "/home/rgottula/dev/track/track/__main__.py", line 134, in main
    tracker.run()
  File "/home/rgottula/dev/track/track/control.py", line 501, in run
    self.target.process_sensor_data()
  File "/home/rgottula/dev/track/track/targets.py", line 657, in process_sensor_data
    _, target_x, target_y = self.camera_target.process_camera_frame()
  File "/home/rgottula/dev/track/track/targets.py", line 513, in process_camera_frame
    keypoints = find_features(frame)
  File "/home/rgottula/dev/track/track/compvis.py", line 41, in find_features
    _, contours, _ = cv2.findContours(
ValueError: not enough values to unpack (expected 3, got 2)
```

Second error:
```
Traceback (most recent call last):
  File "/home/rgottula/dev/venv/bin/track", line 11, in <module>
    load_entry_point('track', 'console_scripts', 'track')()
  File "/home/rgottula/dev/track/track/__main__.py", line 134, in main
    tracker.run()
  File "/home/rgottula/dev/track/track/control.py", line 501, in run
    self.target.process_sensor_data()
  File "/home/rgottula/dev/track/track/targets.py", line 657, in process_sensor_data
    _, target_x, target_y = self.camera_target.process_camera_frame()
  File "/home/rgottula/dev/track/track/targets.py", line 513, in process_camera_frame
    keypoints = find_features(frame)
  File "/home/rgottula/dev/track/track/compvis.py", line 66, in find_features
    keypoints.append(cv2.KeyPoint(center[0], center[1], 2.0*radius))
TypeError: Argument 'x' can not be safely parsed to 'float'
```

**Comment by bgottula** [comment]
I think both of these have been fixed in 13c0b5f8.
